version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: sudo pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python C:\Users\DELL\Downloads\waferFaultDetection (2)\waferFaultDetection\code\WaferFaultDetection_new\tests\test.py  # Adjust the path to your test.py file
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

